rly_file = "GenevaArea.rly"
ttb_files = [ "GenevaWeekday0900.ttb",]
ssn_files = [ "GenevaWeekday0900.ssn",]
img_files = [ "Geneva.bmp",]
doc_files = [ "CornavinPlatformAllocations.png", "LemanExpressNetwork.jpg", "README.md",]
release_date = "2022-02-23"
version = "1.0.0"
country_code = "CH"
factual = true
description = "Representation of the railway network around the city of Geneva, Switzerland operated by SBB CFF FFS."
display_name = "Geneva, Switzerland"
name = "Geneva Area"
author = "Krizar"
contributors = []
